### ISSUE TITLE
feature: exclude times

### ISSUE THREAD

**Issue by resmo** [ngine-io/chaotic#5]
Implement exclude times 

```yaml
---
kind: nomad
dry_run: true
timezone: Europe/Berlin
excludes:
  weekdays:
    - Sun
    - Sat
  times_of_day:
    - 22:00-08:00
    - 11:00-14:00
  days_of_year:
    - Jan1-3
    - Apr1
    - May1
    - Aug1
    - Dec24-31
configs:
  namespace_allowlist:
    - example-prod
  signals:
    - SIGKILL

```
